spring:
  application:
    name: TelegramBotWithAI
  ai:
    openai:
      base-url: https://api.openai.com/v1/chat/completion
      api-key: ${OPENAI_TOKEN}
    deep-seek:
      base-url: https://api.deepseek.com
      token: ${DEEPSEEK_TOKEN}
      contentType: application/json

telegram:
  bot:
    name: hellforge_telegram_gpt_bot
    token: ${TELEGRAM_BOT_TOKEN}